spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/backend
spring.datasource.username=root
spring.datasource.password=root

# JWT
app.jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGRldmVsb3BtZW50IG9ubHk=
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
app.jwt.issuer=backend

# Spring Modulith Events
spring.modulith.events.jdbc.schema-initialization.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Disable banners
spring.main.banner-mode=off
